### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Rachmat04**
Lihat usulan perubahannya di https://commons.wikimedia.org/wiki/Commons_talk:Wiki_Loves_Earth_2017_in_Indonesia#Translation

### CODE REVIEW

**Comment by jayvdb** [comment]
If logged out, when I go to https://commons.wikimedia.org/w/index.php?title=Special:UploadWizard&campaign=wle-id&uselang=id

I only get an error message "Harus masuk log \n
Anda harus masuk log untuk dapat mengunggah berkas."

I do not see a banner.
I do not see anything else relevant to the campaign.

When I visit https://commons.wikimedia.org/wiki/Campaign:wcai-id while logged out, I see the campaign page, and the banner.

**Comment by Rachmat04** [comment]
@jayvdb I suggest you *must* clear your browser cache. In mine, it is displaying the campaign page. Make sure you don't intentionally hide CentralNotice.
61d6ba07-798e-44bd-93a8-ac8a1f9daf75

**Comment by Rachmat04** [comment]
I believe this pull request should be closed right away, as @yakuka has already modified the page I would like to do.

**Comment by jayvdb** [comment]
@Rachmat04 , you must test it when logged out.

**Comment by Rachmat04** [comment]
@jayvdb: I see that. If you click https://commons.wikimedia.org/w/index.php?title=Special:UploadWizard&campaign=wle-id&uselang=id (started with Special:UploadWizard), it required one to log in/create an account. However, if you directly go to https://commons.wikimedia.org/wiki/Campaign:wle-id (namespace Campaign), you can still see the upload page and the banner even you're not logged in.

7277c25d-e401-4842-8748-6dc0d313dfc0

CMIIW

**Pull request closed without merging**
